name: My workflow
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: list and read files
          run: |
           echo "My firts github project"
           ls -ltra
           cat README.md
        
          
